### ISSUE TITLE
[PE-D][Tester A] Participation updated across all students with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-3/tp#140] opened 2022-10-29 04:35 UTC
![Screenshot 2022-10-28 at 5.09.11 PM.png](https://raw.githubusercontent.com/ChryslineLim/ped/main/files/fc7b719a-5509-4e0b-b6ac-983a78a52d70.png)

![Screenshot 2022-10-28 at 5.09.13 PM.png](https://raw.githubusercontent.com/ChryslineLim/ped/main/files/e3c0e406-e12c-4072-b1ae-df4bd39abe10.png)

The command I used was intended to only update Bernice Yu number 2's participation, but Bernice Yu number 3's participation also updated together, although they are different students with different matric numbers.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ChryslineLim/ped#6

**Comment by neosunhan** [comment] 2022-10-29 04:37
Duplicate of #110

**Closed by neosunhan** 2022-10-29 04:37 UTC
